In [4]:
import pandas as pd

In [5]:
posts_df = pd.read_json('r_thinkpad_posts.jsonl', lines=True)
posts_df

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,preview,crosspost_parent,crosspost_parent_list,poll_data,author_cakeday,location_lat,location_long,location_name,outbound_link,websocket_url
0,{'note': 'no_2nd_retrieval'},[],False,NaN,NaN,False,Vulkiim,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'note': 'no_2nd_retrieval'},[],False,NaN,NaN,False,walshe2004,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'note': 'no_2nd_retrieval'},[],False,NaN,NaN,False,Healthy_Lettuce_9078,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'note': 'no_2nd_retrieval'},[],False,NaN,NaN,False,KCniteGambler,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'note': 'no_2nd_retrieval'},[],False,NaN,NaN,False,Automatic_Sky286,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79344,NaN,[],False,NaN,NaN,False,Deghimon,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79345,NaN,[],False,NaN,NaN,False,Deghimon,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,wss://k8s-lb.wss.redditmedia.com/link/1sd9x9a?...
79346,NaN,[],False,NaN,NaN,False,BuyingStuffIShouIdnt,None,None,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'url': 'https://www.reddit.com/gallery/1sdb57...,wss://k8s-lb.wss.redditmedia.com/link/1sdb57v?...
79347,NaN,[],False,NaN,NaN,False,saekkura,None,None,[],...,{'images': [{'source': {'url': 'https://previe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'url': 'https://i.redd.it/6eioogqt0ftg1.jpeg'...,wss://k8s-lb.wss.redditmedia.com/link/1sdb5r1?...
79348,NaN,[],False,NaN,NaN,False,SharktasticA,None,none,"[{'e': 'text', 't': '365ED/380Z/A30p/W700/W530...",...,{'images': [{'source': {'url': 'https://previe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'url': 'https://i.redd.it/vbsimxwy1ftg1.png',...",wss://k8s-lb.wss.redditmedia.com/link/1sdbbws?...

In [6]:
comments_df = pd.read_json('r_thinkpad_comments.jsonl', lines=True)
comments_df

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,unrepliable_reason,ups,user_reports,author_cakeday,editable,body_sha1,nest_level,media_metadata,profile_img,profile_over_18
0,{'retrieved_2nd_on': 1704196947},[],NaN,NaN,False,NaN,hax0rz_,None,none,"[{'e': 'text', 't': 'T480, X230, T420, T410, T...",...,NaN,2,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'retrieved_2nd_on': 1704197040},[],NaN,NaN,False,NaN,boundbybricks,None,None,[],...,NaN,8,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'retrieved_2nd_on': 1704197067},[],NaN,NaN,False,NaN,FedsAgainstGunS,None,none,"[{'e': 'text', 't': 'X60 X60t X61s X200t T410 ...",...,NaN,18,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'retrieved_2nd_on': 1704197083},[],NaN,NaN,False,NaN,Prize-Tone9910,None,None,[],...,NaN,2,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'retrieved_2nd_on': 1704197124},[],NaN,NaN,False,NaN,sekulicb,None,None,[],...,NaN,1,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736312,NaN,[],NaN,NaN,False,NaN,BuyingStuffIShouIdnt,None,None,[],...,NaN,1,[],NaN,NaN,NaN,NaN,NaN,https://www.redditstatic.com/avatars/defaults/...,0.0
736313,NaN,[],NaN,NaN,False,NaN,BuyingStuffIShouIdnt,None,None,[],...,NaN,1,[],NaN,NaN,NaN,NaN,NaN,https://www.redditstatic.com/avatars/defaults/...,0.0
736314,NaN,[],NaN,NaN,False,NaN,SaNch0sE,None,none,"[{'e': 'text', 't': 'L14 Gen 2a'}]",...,NaN,1,[],NaN,NaN,NaN,NaN,NaN,https://styles.redditmedia.com/t5_ygb4z/styles...,0.0
736315,NaN,[],NaN,NaN,False,NaN,BuyingStuffIShouIdnt,None,None,[],...,NaN,1,[],NaN,NaN,NaN,NaN,NaN,https://www.redditstatic.com/avatars/defaults/...,0.0
736316,NaN,[],NaN,NaN,False,NaN,BuyingStuffIShouIdnt,None,None,[],...,NaN,1,[],NaN,NaN,NaN,NaN,NaN,https://www.redditstatic.com/avatars/defaults/...,0.0